### ISSUE TITLE
more intuitive handling of dates (creation, update, publication, etc.)

### ISSUE THREAD

**Issue by andrewsu** [SuLab/outbreak.info#112]
Currently, we have many publications with dates in the future (because we use the "datePublished" from the pubmed record), and that is a bit non-intuitive for users.  I'd like to try out some ways of improving how we handle those publication dates.  For example, @flaneuse suggests creating a new date field based on "dateModified || datePublished || dateCreated, in that order, so long as the date is <= today".  That would seem pretty reasonable, but certainly open to other ideas too...

**Comment by andrewsu** [comment]
Since having multiple dates applies to many resource types (including publications, clinical trials, and datasets), presumably we should create some ES-wide solution rather than leaving this to each individual parser. @namespacestd0 do you agree?

**Comment by flaneuse** [comment]
All parsers / crawlers now go through an ES transformation pipeline when adding to ES index.
