### ISSUE TITLE
Data Update Issue

### ISSUE THREAD

**Issue by mmayers12** [SuLab/outbreak.info#31]
Your latest data update seems to have an issue. It looks to have grabbed the same numbers as today (1h ago) as yesterday's update.

All the day over day increases are 0 or minimal. 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/8902458/77388140-7ec4f300-6d4c-11ea-800f-e6d01db78742.png">

**Comment by flaneuse** [comment]
Yep, underlying data model changed dramatically, filling today's data with a column of 0s, so we're re-writing API :(.   ETA end of the week at the latest.

**Comment by gkarthik** [comment]
Refer https://github.com/CSSEGISandData/COVID-19/issues/1250. Turns out "upcoming changes" were implemented today.

**Comment by flaneuse** [comment]
fixed with #36
