### ISSUE TITLE
add disclaimer

### ISSUE THREAD

**Issue by andrewsu** [SuLab/outbreak.info#35]
From our legal department: 

> Disclaimer:
>
> Every effort has been made to ensure the accuracy and completeness of the information and data provided on this website. However, Scripps Research makes no warranties, expressed or implied, regarding errors or omissions and assume no legal liability or responsibility for loss or damage resulting from the use or misuse of information contained within. Scripps Research reserves the right to revise the data pursuant to further analysis and review.

privacy policy and terms of use to come...

**Comment by flaneuse** [comment]
fixed with https://github.com/SuLab/outbreak.info/commit/d0c0bbe9eed575bddf11d7c3c3d44af4839ea367
