### ISSUE TITLE
Calculate days since X number of cases/deaths on API

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info#42]

**Comment by gkarthik** [comment]
Fixed by https://github.com/gkarthik/biothings_covid19/commit/c729ac28e9bfb8edde9aeeb72cc190644613264b

**Comment by andrewsu** [comment]
Saw this visualization that aligned the x-axis according to "X number of cases/deaths per Y number of residents". Not sure it's worth implementing, but I can definitely see the rationale. A threshold of 100 cases is very different in California vs Wyoming (or China vs Denmark).

https://twitter.com/mattyglesias/status/1248075339445817344?s=19

**Comment by andrewsu** [comment]
And an interesting twitter thread by Carl Bergstrom (and replies) that suggest that normalizing by population size may _not_ be a good metric.

https://twitter.com/CT_Bergstrom/status/1249480343968575488

(sorry, not sure why I'm capturing these here in a closed issue... 🤷‍♂️)

**Comment by gkarthik** [comment]
I agree with what he's saying but I also think its more convoluted than that. The best way to track raw case numbers would be by "epicenters" of the outbreak. The US does not have 1 epicenter for the pandemic. For example, for the US we might consider the following epicenters: New York, Los Angeles, Seattle, San Diego. Looking at how raw case counts are increasing at "epicenters" might make more sense. However, figuring out epi centers is tricky so we generally settle for the highest geo resolution we can get: county/metro area in this case. 

Factors like "density of population" will also significantly change how the raw numbers reflect intervention strategies. Haven't yet translated this into code but I do agree that normalizing case counts isn't trivial.
