### ISSUE TITLE
Improve cases/deaths/recoveries groupings of sub-data In “latest data” chart

### ISSUE THREAD

**Issue by jdg2107** [SuLab/outbreak.info#62]
Improve cases/deaths/recoveries groupings of sub-data (total/increase/change over time) in “latest data” chart. 

For example, “recoveries” contains no data underneath.

Tested on: iPhone XS - Safari and Chrome mobile browsers.

**Comment by gkarthik** [comment]
Thank you for pointing this out. We're fixing this this at #61
