### ISSUE TITLE
getAll() pulls from date 3/24 so regions added after are missing in search

### ISSUE THREAD

**Issue by gkarthik** [SuLab/outbreak.info#67]
Fail case: Search for Myanmar (iso3: MMR).
https://outbreak.info/epidemiology?location=MMR

Possibly relevant line numbers.
https://github.com/SuLab/outbreak.info/blob/master/web/src/api/epi-geo.js#L28

**Comment by flaneuse** [comment]
@gkarthik do we want to handle this on the front-end (2 API calls to get date and then execute) or backend (remove `confirmed_currentIncrease` etc. and create a `mostRecent` tag or similar?
