### ISSUE TITLE
"Data aggregation"

### ISSUE THREAD

**Issue by nnpok** [SuLab/outbreak.info#68]
It looks like the data is singly sourced from JHU right now—is the idea that multiple data sources will be merged and aggregated?

**Comment by gkarthik** [comment]
Yes, we're in the process of aggregating from multiple data sources. If you have any specific source you'd like to see. Please let us know!

**Comment by nnpok** [comment]
There's these three I've been sourcing for my research, in addition to the JHU set:

https://github.com/nytimes/covid-19-data
https://covidtracking.com/
https://github.com/beoutbreakprepared/nCoV2019/tree/master/latest_data

In case you wanted to add those... how do you plan on merging data/ensuring quality? Would love to just use your superset of data.

**Comment by gkarthik** [comment]
We will be integrating testing data from covidtracking and county level data from NYT. Please refer to issues labeled [data](https://github.com/SuLab/outbreak.info/issues?q=is%3Aopen+is%3Aissue+label%3Adata) to see what we have planned!

**Comment by andrewsu** [comment]
Jotting down two other sources for discussion

https://www.worldometers.info/coronavirus/
https://github.com/neherlab/covid19_scenarios_data
