### ISSUE TITLE
"At Glance" section shows max. 4 graphs, but allows more to be added

### ISSUE THREAD

**Issue by sirloon** [SuLab/outbreak.info#70]
![image](https://user-images.githubusercontent.com/2883770/78052854-8ed46800-7334-11ea-9284-7713885987a0.png)

Clicking on "Change Locations" will allow to add another location, but only 4 are displayed after validation.

**Comment by flaneuse** [comment]
@sirloon what do you mean after validation?  i can add more than 4.
<img width="1318" alt="Screenshot 2020-03-31 09 51 18" src="https://user-images.githubusercontent.com/8041065/78053310-44072000-7335-11ea-85be-7652ad43057e.png">
