### ISSUE TITLE
Incorporate Hospitalization Data

### ISSUE THREAD

**Issue by azxu** [SuLab/outbreak.info#76]
Would be great to incorporate hospitalization data (perhaps from https://covidtracking.com/) so that we can visualize that data using your interface (which is great).

Case count data not very predictive right now given poor testing & death data lags by quite a bit of time. The covidtracking.com hospitalization data is not perfect but best state-by-state source readily available.

**Comment by gkarthik** [comment]
Thank you for raising the issue. We're in the process of aggregating data from covidtracking for US states. We should have a release soon with that data incorporated too.

**Comment by sundaram-covid19-biohack** [comment]
Hello @flaneuse , @gkarthik , @andrewsu , 

I followed the issues link from here:
https://github.com/virtual-biohackathons/covid-19-bh20/wiki/Web-Development

Please advise: are there any Python-specific tasks/issues I can help out with?

Thank you,
Jay

**Comment by andrewsu** [comment]
@sundaram-covid19-biohack sorry for the late reply -- in discussions with the team, one potential project might be writing a data parser described in https://github.com/SuLab/outbreak.info-resources/issues/19. If you're interested, let's move all followup discussion on this topic over there...
